apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-linux-amd64 convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: room
  name: room
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    io.kompose.service: room
status:
  loadBalancer: {}
