apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-linux-amd64 convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: storage
  name: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: storage
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-linux-amd64 convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/kompose-default: "true"
        io.kompose.service: storage
    spec:
      containers:
        - env:
            - name: PORT
              value: "8081"
          image: quay.apps.mgmt1.ocp.trafikverket.local/registry-1.docker.io/alswl/excalidraw-storage-backend:v2023.11.11
          name: storage
          ports:
            - containerPort: 8081
              hostPort: 8081
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
